{
    'name': "MRP Alpacasa",
    'version': "1.0",
    'category': 'Manufacturing/Manufacturing',
    'sequence': 15,
    'author': "Alpacasa",
    'summary': """Modificaciones para reporte hechas por Alpacasa""",
    'depends': ['quality_control',
                'product',
                'stock',
                'stock_account',
                'resource',
                'mrp',
                'quality',
                'stock_landed_costs'],
    'data': [
        'wizard/wizard_report_views.xml',
        'wizard/wizard_report_alpacasa_views.xml',
        'wizard/produccion_reporte_views.xml',
        'reports/report_superalimentos.xml',
        'reports/config_report.xml',
        'wizard/wizard_report_granos_views.xml',
    ],
    'installable': True,
    'auto_install': False,
}
